### PR TITLE
MNT: Re-rendered with conda-build 3.18.10, conda-smithy 3.6.2, and co…

### PR DESCRIPTION
**Pull request by kayarre**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

<code>@<space/>conda-forge-admin, please rerender</code>

### CODE REVIEW

**Comment by wolfv** [comment]
Hi, great! Thanks.

Is there a particular need for this rebuild?
I'm happy to merge it otherwise!

**Comment by kayarre** [comment]
I am new at this. I was trying to update the version.

**Comment by wolfv** [comment]
okay! did you change meta.yaml in the recipe folder? usually you'll have to replace the version and SHA256 sums:

https://github.com/conda-forge/openexr-feedstock/blob/master/recipe/meta.yaml

you can find the sha256 sum by downloading the tarball, and running `sha256sum myfile.tar.gz` on the (Linux) command line (not sure what the command would be for OS X or Windows).

**Comment by kayarre** [comment]
I did and I did update the sha256sum.

**Comment by wolfv** [comment]
then you might need to push these changes? I checked 3 times now, I can't see `meta.yaml` in this PR :)

**Comment by kayarre** [comment]
Closing, am not sure what I did wrong.

**Comment by wolfv** [comment]
maybe what you were missing is:

```
git add recipe/meta.yaml
git commit -am 'update openexr version'
git push
```

Would be great if you could add the updated meta.yaml! Then the new version will be released.

**Comment by wolfv** [comment]
if you check your branch, it still has the current meta.yaml: 

https://github.com/kayarre/openexr-feedstock/tree/master/recipe

**Pull request closed without merging**
